###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID il2225ht25_jcdavid)
#  Generated on:      Thu Dec 18 10:36:07 2025
#  Design:            drra_wrapper
#  Command:           report_constraint > ../phy/rpt/flat_sweep/drra_wrapper_constraint_4000.sdc
###############################################################
# format : frame 0 : split 0

max_delay/setup
---------------------------
      -------------------------------------------------------------------------------------------------------------------------------------------  
       End Point                                  Slack                                         Cause                                       View   
      -------------------------------------------------------------------------------------------------------------------------------------------  
      Silago_top_inst_6_0/SILEGO_cell/MTRF_cell/dpu_gen/U_NACU_0/acc_out_reg[0]/D r   -887.744   VIOLATED                                   AVF_RCWORST
      -------------------------------------------------------------------------------------------------------------------------------------------

Check type : clock_period
---------------------------
No paths found

Check type : skew
---------------------------
No paths found

Check type : pulse_width
---------------------------
   ----------------------------------------------------------------------------------------------  
                           SEQUENTIAL CLOCK PULSE WIDTH                                            
   ----------------------------------------------------------------------------------------------  
    Pin                                Required     Actual Pulse      Slack       View Name        
                                      Pulse Width      Width                                       
   ----------------------------------------------------------------------------------------------  
   Silago_top_inst_2_0/dimarch_data_in_out_reg[158]/CLK (low)    227.506        1959.595       1732.089       AVF_RCWORST
   ----------------------------------------------------------------------------------------------

Check type : max_transition
---------------------------
  Pin : Silago_top_inst_4_0/u_data_selector/U495/A1 	 View : AVF_RCWORST
 
   max_transition :   517.736
- Transition Time:  1247.100
-----------------------------------------------------
  slack          :  -729.364 ( VIOLATED )

Check type : max_capacitance
---------------------------
  Pin : Silago_bot_inst_4_1/SILEGO_cell/MTRF_cell/U562/Z 	 View : AVF_RCWORST
 
   max_capacitance :    36.909
- Capacitance     :    72.747
-----------------------------------------------------
  slack          :   -35.838 ( VIOLATED )

Check type : max_fanout
---------------------------
 No Check found
