###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID il2225ht25_jcdavid)
#  Generated on:      Wed Dec 17 18:11:36 2025
#  Design:            drra_wrapper
#  Command:           report_constraint > ../phy/rpt/flat_sweep/drra_wrapper_constraint_12000.sdc
###############################################################
# format : frame 0 : split 0

max_delay/setup
---------------------------
      -------------------------------------------------------------------------------------------------------------------------------------------  
       End Point                                  Slack                                         Cause                                       View   
      -------------------------------------------------------------------------------------------------------------------------------------------  
      Silago_top_inst_2_0/SILEGO_cell/MTRF_cell/dpu_gen/U_NACU_0/U_divider/division/U_DIV/clk_r_REG120_S1/D r   -349.210   VIOLATED                                   AVF_RCWORST
      -------------------------------------------------------------------------------------------------------------------------------------------

Check type : clock_period
---------------------------
No paths found

Check type : skew
---------------------------
No paths found

Check type : pulse_width
---------------------------
   ----------------------------------------------------------------------------------------------  
                           SEQUENTIAL CLOCK PULSE WIDTH                                            
   ----------------------------------------------------------------------------------------------  
    Pin                                Required     Actual Pulse      Slack       View Name        
                                      Pulse Width      Width                                       
   ----------------------------------------------------------------------------------------------  
   Silago_top_inst_2_0/SILEGO_cell/MTRF_cell/dpu_gen/U_NACU_0/U_divider/division/U_DIV/clk_r_REG74_S2/CLK (low)    198.432        5880.963       5682.532       AVF_RCWORST
   ----------------------------------------------------------------------------------------------

Check type : max_transition
---------------------------
  Pin : Silago_top_inst_6_0/u_bus_selector/U125/A1 	 View : AVF_RCWORST
 
   max_transition :   517.736
- Transition Time:  1037.600
-----------------------------------------------------
  slack          :  -519.864 ( VIOLATED )

Check type : max_capacitance
---------------------------
  Pin : Silago_bot_inst_6_1/SILEGO_cell/MTRF_cell/shadowReg/U342/Z 	 View : AVF_RCWORST
 
   max_capacitance :    37.113
- Capacitance     :    60.658
-----------------------------------------------------
  slack          :   -23.545 ( VIOLATED )

Check type : max_fanout
---------------------------
 No Check found
