###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID il2225ht25_jcdavid)
#  Generated on:      Wed Dec 17 02:17:28 2025
#  Design:            drra_wrapper
#  Command:           report_constraint > ../phy/rpt/flat_sweep/drra_wrapper_constraint_24000.sdc
###############################################################
# format : frame 0 : split 0

max_delay/setup
---------------------------
      -------------------------------------------------------------------------------------------------------------------------------------------  
       End Point                                  Slack                                         Cause                                       View   
      -------------------------------------------------------------------------------------------------------------------------------------------  
      Silago_top_inst_2_0/SILEGO_cell/MTRF_cell/dpu_gen/U_NACU_0/U_divider/division/U_DIV/clk_r_REG12_S3/D r   160.914    MET                                        AVF_RCWORST
      -------------------------------------------------------------------------------------------------------------------------------------------

Check type : clock_period
---------------------------
No paths found

Check type : skew
---------------------------
No paths found

Check type : pulse_width
---------------------------
   ----------------------------------------------------------------------------------------------  
                           SEQUENTIAL CLOCK PULSE WIDTH                                            
   ----------------------------------------------------------------------------------------------  
    Pin                                Required     Actual Pulse      Slack       View Name        
                                      Pulse Width      Width                                       
   ----------------------------------------------------------------------------------------------  
   Silago_top_inst_2_0/SILEGO_cell/MTRF_cell/dpu_gen/U_NACU_0/U_divider/division/U_DIV/clk_r_REG193_S2/CLK (low)    196.238        11757.996      11561.758      AVF_RCWORST
   ----------------------------------------------------------------------------------------------

Check type : max_transition
---------------------------
  Pin : Silago_top_inst_5_0/u_data_selector/U413/A1 	 View : AVF_RCWORST
 
   max_transition :   517.736
- Transition Time:   831.900
-----------------------------------------------------
  slack          :  -314.164 ( VIOLATED )

Check type : max_capacitance
---------------------------
  Pin : Silago_bot_inst_5_1/SILEGO_cell/MTRF_cell/U525/Z 	 View : AVF_RCWORST
 
   max_capacitance :    36.909
- Capacitance     :    48.930
-----------------------------------------------------
  slack          :   -12.021 ( VIOLATED )

Check type : max_fanout
---------------------------
 No Check found
