###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID il2225ht25_jcdavid)
#  Generated on:      Wed Dec 17 23:29:19 2025
#  Design:            drra_wrapper
#  Command:           report_constraint > ../phy/rpt/flat_sweep/drra_wrapper_constraint_8000.sdc
###############################################################
# format : frame 0 : split 0

max_delay/setup
---------------------------
      -------------------------------------------------------------------------------------------------------------------------------------------  
       End Point                                  Slack                                         Cause                                       View   
      -------------------------------------------------------------------------------------------------------------------------------------------  
      Silago_top_inst_1_0/SILEGO_cell/MTRF_cell/dpu_gen/U_NACU_0/acc_out_reg[16]/D r   -199.129   VIOLATED                                   AVF_RCWORST
      -------------------------------------------------------------------------------------------------------------------------------------------

Check type : clock_period
---------------------------
No paths found

Check type : skew
---------------------------
No paths found

Check type : pulse_width
---------------------------
   ----------------------------------------------------------------------------------------------  
                           SEQUENTIAL CLOCK PULSE WIDTH                                            
   ----------------------------------------------------------------------------------------------  
    Pin                                Required     Actual Pulse      Slack       View Name        
                                      Pulse Width      Width                                       
   ----------------------------------------------------------------------------------------------  
   Silago_bot_inst_4_1/SILEGO_cell/MTRF_cell/dpu_gen/U_NACU_0/U_divider/division/U_DIV/clk_r_REG125_S3/CLK (low)    189.049        3919.321       3730.272       AVF_RCWORST
   ----------------------------------------------------------------------------------------------

Check type : max_transition
---------------------------
  Pin : Silago_top_inst_3_0/u_data_selector/U501/A1 	 View : AVF_RCWORST
 
   max_transition :   517.736
- Transition Time:  1453.300
-----------------------------------------------------
  slack          :  -935.564 ( VIOLATED )

Check type : max_capacitance
---------------------------
  Pin : Silago_bot_inst_3_1/SILEGO_cell/MTRF_cell/U535/Z 	 View : AVF_RCWORST
 
   max_capacitance :    36.909
- Capacitance     :    84.765
-----------------------------------------------------
  slack          :   -47.857 ( VIOLATED )

Check type : max_fanout
---------------------------
 No Check found
