###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID il2225ht25_jcdavid)
#  Generated on:      Tue Dec 16 21:05:16 2025
#  Design:            drra_wrapper
#  Command:           report_constraint > ../phy/rpt/flat_sweep/drra_wrapper_constraint_28000.sdc
###############################################################
# format : frame 0 : split 0

max_delay/setup
---------------------------
      -------------------------------------------------------------------------------------------------------------------------------------------  
       End Point                                  Slack                                         Cause                                       View   
      -------------------------------------------------------------------------------------------------------------------------------------------  
      Silago_bot_l_corner_inst_0_1/SILEGO_cell/MTRF_cell/dpu_gen/U_NACU_0/U_divider/division/U_DIV/clk_r_REG9_S3/D r   264.846    MET                                        AVF_RCWORST
      -------------------------------------------------------------------------------------------------------------------------------------------

Check type : clock_period
---------------------------
No paths found

Check type : skew
---------------------------
No paths found

Check type : pulse_width
---------------------------
   ----------------------------------------------------------------------------------------------  
                           SEQUENTIAL CLOCK PULSE WIDTH                                            
   ----------------------------------------------------------------------------------------------  
    Pin                                Required     Actual Pulse      Slack       View Name        
                                      Pulse Width      Width                                       
   ----------------------------------------------------------------------------------------------  
   Silago_bot_inst_6_1/SILEGO_cell/MTRF_cell/dpu_gen/U_NACU_0/U_divider/division/U_DIV/clk_r_REG204_S1/CLK (high)    191.483        13717.724      13526.240      AVF_RCWORST
   ----------------------------------------------------------------------------------------------

Check type : max_transition
---------------------------
  Pin : Silago_top_l_corner_inst_0_0/u_data_selector/U579/A1 	 View : AVF_RCWORST
 
   max_transition :   517.736
- Transition Time:  1268.100
-----------------------------------------------------
  slack          :  -750.364 ( VIOLATED )

Check type : max_capacitance
---------------------------
  Pin : Silago_bot_l_corner_inst_0_1/SILEGO_cell/MTRF_cell/U581/Z 	 View : AVF_RCWORST
 
   max_capacitance :    36.909
- Capacitance     :    73.731
-----------------------------------------------------
  slack          :   -36.823 ( VIOLATED )

Check type : max_fanout
---------------------------
 No Check found
