###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID il2225ht25_jcdavid)
#  Generated on:      Wed Dec 17 07:30:57 2025
#  Design:            drra_wrapper
#  Command:           report_constraint > ../phy/rpt/flat_sweep/drra_wrapper_constraint_20000.sdc
###############################################################
# format : frame 0 : split 0

max_delay/setup
---------------------------
      -------------------------------------------------------------------------------------------------------------------------------------------  
       End Point                                  Slack                                         Cause                                       View   
      -------------------------------------------------------------------------------------------------------------------------------------------  
      Silago_bot_r_corner_inst_7_1/SILEGO_cell/MTRF_cell/dpu_gen/U_NACU_0/U_divider/division/U_DIV/clk_r_REG11_S3/D r   99.668     MET                                        AVF_RCWORST
      -------------------------------------------------------------------------------------------------------------------------------------------

Check type : clock_period
---------------------------
No paths found

Check type : skew
---------------------------
No paths found

Check type : pulse_width
---------------------------
   ----------------------------------------------------------------------------------------------  
                           SEQUENTIAL CLOCK PULSE WIDTH                                            
   ----------------------------------------------------------------------------------------------  
    Pin                                Required     Actual Pulse      Slack       View Name        
                                      Pulse Width      Width                                       
   ----------------------------------------------------------------------------------------------  
   Silago_bot_l_corner_inst_0_1/SILEGO_cell/MTRF_cell/dpu_gen/U_NACU_0/U_divider/division/U_DIV/clk_r_REG7_S3/CLK (low)    192.580        9799.071       9606.491       AVF_RCWORST
   ----------------------------------------------------------------------------------------------

Check type : max_transition
---------------------------
  Pin : Silago_top_inst_5_0/u_data_selector/U383/A1 	 View : AVF_RCWORST
 
   max_transition :   517.736
- Transition Time:  1376.000
-----------------------------------------------------
  slack          :  -858.264 ( VIOLATED )

Check type : max_capacitance
---------------------------
  Pin : Silago_bot_inst_5_1/SILEGO_cell/MTRF_cell/U510/Z 	 View : AVF_RCWORST
 
   max_capacitance :    36.909
- Capacitance     :    80.056
-----------------------------------------------------
  slack          :   -43.147 ( VIOLATED )

Check type : max_fanout
---------------------------
 No Check found
