###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID il2225ht25_jcdavid)
#  Generated on:      Fri Dec 12 19:42:42 2025
#  Design:            drra_wrapper
#  Command:           write_db ../phy/db/drra_wrapper.dat
###############################################################
current_design drra_wrapper
create_clock [get_ports {clk}]  -name clk -period 20000.000000 -waveform {0.000000 10000.000000}
set_propagated_clock  [get_ports {clk}]
set_clock_uncertainty 200 [get_clocks {clk}]
set_false_path  -from [get_ports {rst_n}] 
