###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID il2225ht25_jcdavid)
#  Generated on:      Sat Jan  3 07:52:41 2026
#  Design:            drra_wrapper
#  Command:           report_constraint > ../phy/rpt/drra_wrapper_constraint.sdc
###############################################################
# format : frame 0 : split 0

max_delay/setup
---------------------------
      -------------------------------------------------------------------------------------------------------------------------------------------  
       End Point                                  Slack                                         Cause                                       View   
      -------------------------------------------------------------------------------------------------------------------------------------------  
      Silago_bot_r_corner_inst_7_1/SILEGO_cell/MTRF_cell/dpu_gen/U_NACU_0/U_divider/division/U_DIV/dpu_gen_U_NACU_0_U_divider_division_link211662_r_REG171_S1/D r   -65.816    VIOLATED                                   AVF_RCWORST
      -------------------------------------------------------------------------------------------------------------------------------------------

Check type : clock_period
---------------------------
No paths found

Check type : skew
---------------------------
No paths found

Check type : pulse_width
---------------------------
   ----------------------------------------------------------------------------------------------  
                           SEQUENTIAL CLOCK PULSE WIDTH                                            
   ----------------------------------------------------------------------------------------------  
    Pin                                Required     Actual Pulse      Slack       View Name        
                                      Pulse Width      Width                                       
   ----------------------------------------------------------------------------------------------  
   Silago_bot_inst_6_1/SILEGO_cell/config_swb/sel_r_int_reg[2][4]/CLK (low)    90.963         9792.891       9701.928       AVF_RCWORST
   ----------------------------------------------------------------------------------------------

Check type : max_transition
---------------------------
  Pin : Silago_top_inst_3_0/u_data_selector/FE_OFC1251_data_in_next_105/A 	 View : AVF_RCWORST
 
   max_transition :   517.736
- Transition Time:  1805.300
-----------------------------------------------------
  slack          : -1287.564 ( VIOLATED )

Check type : max_capacitance
---------------------------
  Pin : Silago_bot_inst_3_1/SILEGO_cell/MTRF_cell/U935/Z 	 View : AVF_RCWORST
 
   max_capacitance :    32.640
- Capacitance     :    93.863
-----------------------------------------------------
  slack          :   -61.223 ( VIOLATED )

Check type : max_fanout
---------------------------
 No Check found
