###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID il2225ht25_jcdavid)
#  Generated on:      Fri Dec 12 20:27:02 2025
#  Design:            drra_wrapper
#  Command:           report_constraint > ../phy/rpt/drra_wrapper_constraint.sdc
###############################################################
# format : frame 0 : split 0

max_delay/setup
---------------------------
      -------------------------------------------------------------------------------------------------------------------------------------------  
       End Point                                  Slack                                         Cause                                       View   
      -------------------------------------------------------------------------------------------------------------------------------------------  
      Silago_bot_inst_1_1/SILEGO_cell/MTRF_cell/dpu_gen/U_NACU_0/U_divider/division/U_DIV/clk_r_REG12_S3/D r   -13749.336 VIOLATED                                   AVF_RCWORST
      -------------------------------------------------------------------------------------------------------------------------------------------

Check type : clock_period
---------------------------
No paths found

Check type : skew
---------------------------
No paths found

Check type : pulse_width
---------------------------
   ----------------------------------------------------------------------------------------------  
                           SEQUENTIAL CLOCK PULSE WIDTH                                            
   ----------------------------------------------------------------------------------------------  
    Pin                                Required     Actual Pulse      Slack       View Name        
                                      Pulse Width      Width                                       
   ----------------------------------------------------------------------------------------------  
   Silago_top_inst_3_0/SILEGO_cell/MTRF_cell/seq_gen/instr_reg_reg[28][22]/CLK (low)    172.352        9799.173       9626.821       AVF_RCWORST
   ----------------------------------------------------------------------------------------------

Check type : max_transition
---------------------------
  Pin : Silago_top_inst_4_0/SILEGO_cell/MTRF_cell/reg_top/RegisterFile/U1371/C1 	 View : AVF_RCWORST
 
   max_transition :   517.736
- Transition Time:  8404.200
-----------------------------------------------------
  slack          : -7886.464 ( VIOLATED )

Check type : max_capacitance
---------------------------
  Pin : Silago_bot_r_corner_inst_7_1/U2/Z 	 View : AVF_RCWORST
 
   max_capacitance :   171.899
- Capacitance     :  1666.061
-----------------------------------------------------
  slack          : -1494.162 ( VIOLATED )

Check type : max_fanout
---------------------------
 No Check found
